{"name": "Проверка на логин не существующим пользователем", "status": "passed", "description": "Проверка на ошибку, соответствие статус-кода и ответа", "start": 1727014023947, "stop": 1727014024243, "uuid": "a6dc8e08-3524-4cdf-a61b-3de16d403548", "historyId": "6d294a95f71433e43dfe19df844c4763", "testCaseId": "6d294a95f71433e43dfe19df844c4763", "fullName": "tests.test_user_login.TestUserLogin#test_user_non_existing_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "FanatovPC"}, {"name": "thread", "value": "10880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}